Traceback (most recent call last):
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from benchtools.src.plotools import image_grid

# Definimos el path de las imagenes
PATH_FIGURES = '../../figuras/'
------------------

[1;31m---------------------------------------------------------------------------[0m
<<<<<<< HEAD:tesis/_build/html/reports/comparacion-algoritmos.log
[1;31mImportError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_5020/3717301343.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mbenchtools[0m[1;33m.[0m[0msrc[0m[1;33m.[0m[0mplotools[0m [1;32mimport[0m [0mimage_grid[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [1;31m# Definimos el path de las imagenes[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mPATH_FIGURES[0m [1;33m=[0m [1;34m'../../figuras/'[0m[1;33m[0m[1;33m[0m[0m

[1;31mImportError[0m: cannot import name 'image_grid' from 'benchtools.src.plotools' (c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\benchtools\src\plotools.py)
ImportError: cannot import name 'image_grid' from 'benchtools.src.plotools' (c:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\benchtools\src\plotools.py)
=======
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_27800/3995052973.py[0m in [0;36m<module>[1;34m[0m
[0;32m      7[0m [1;31m# Funciones de benchtools[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [1;32mfrom[0m [0mbenchtools[0m[1;33m.[0m[0msrc[0m[1;33m.[0m[0mplotools[0m [1;32mimport[0m [0mbkg_sig_hist[0m[1;33m,[0m [0mbkg_sig_scatter[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m [1;32mfrom[0m [0mbenchtools[0m[1;33m.[0m[0msrc[0m[1;33m.[0m[0mclustering[0m [1;32mimport[0m [0mbuild_features[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mc:\users\maria\appdata\local\programs\python\python37-32\lib\site-packages\benchtools\src\clustering.py[0m in [0;36m<module>[1;34m[0m
[0;32m      4[0m [1;32mfrom[0m [0mtqdm[0m [1;32mimport[0m [0mtqdm[0m  [1;31m# Progress bar[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mnumpy[0m[1;33m.[0m[0mcore[0m[1;33m.[0m[0mrecords[0m [1;32mimport[0m [0mfromstring[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m [1;32mimport[0m [0mpyjet[0m [1;32mas[0m [0mfj[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      7[0m [1;32mfrom[0m [0mbenchtools[0m[1;33m.[0m[0msrc[0m[1;33m.[0m[0msubstructure[0m [1;32mimport[0m [0mdeltaR[0m[1;33m,[0m [0mtau21[0m[1;33m,[0m [0minvariantmass[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [1;32mfrom[0m [0mbenchtools[0m[1;33m.[0m[0msrc[0m[1;33m.[0m[0mdatatools[0m [1;32mimport[0m [0mgenerator[0m[1;33m,[0m [0msave_df[0m[1;33m,[0m [0mascii_column[0m[1;33m,[0m [0mmerge_files[0m[1;33m,[0m [0mdelete_multifiles[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\pyjet\__init__.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m from ._libpyjet import (ClusterSequence, ClusterSequenceArea,
[0m[0;32m      2[0m                         [0mJetDefinition[0m[1;33m,[0m [0mPseudoJet[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m                         DTYPE, DTYPE_PTEPM, DTYPE_EP, USING_EXTERNAL_FASTJET)
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [1;33m.[0m[0m_version[0m [1;32mimport[0m [0m__version__[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pyjet._libpyjet'
ModuleNotFoundError: No module named 'pyjet._libpyjet'
>>>>>>> analisis-datos:tesis/_build/html/reports/conjunto-RnD.log

